language: java
jdk:
  - oraclejdk8
sudo: required
cache:
  directories:
    - $HOME/.m2
install: true
before_script: ./mvnw install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script: ./mvnw install -q -nsu -Dmaven.test.redirectTestOutputToFile=true
dist: trusty
